#unit:[m] 
map_shape : [5,5]
origin_pose: [2.5,2.5,0]   
goal_pose: [1.5,1.5,0]
ROB_init_dict: {'type': 'ROB', 'pose': [1.5, -1.5, 180]}
MO_init_dicts_list: [{'type': 'MOa' , 'pose': [-1.85, 1, 90]},
                     {'type': 'MOa' , 'pose': [-1, -1.1, 90]},
                     {'type': 'MOa' , 'pose': [-1, -0.3, 0]},
                     {'type': 'MOc' , 'pose': [0.7, -1.85, 0]},
                     {'type': 'MOc' , 'pose': [0.7, 1.85, 0]},
                     {'type': 'MOC' , 'pose': [-1.4, 1.85, 0]}]