real_resolution: 40         #unit:[pxl/m]
dijkstra_resolution: 5      #unit:[pxl/cell]
origin_pxl: [100,100]       #unit:[pxl/pxl] (row,col)
#unit:[m] for everything below
goal_init_pos: [1,1.5]
ROB_init_dict: {'name': 'ROB', 'pose': [1, -1.5, 180]}
MO_init_dicts_list: [{'name': 'MO1' , 'pose': [-1.5, 0, 90]}]