real_resolution: 40         #unit:[pxl/m]
dijkstra_resolution: 5      #unit:[pxl/cell]
#unit:[m] for everything below
origin_pose: [2.5,2.5,0]   
goal_pose: [1,1.5,0]
ROB_init_dict: {'type': 'ROB', 'pose': [1, -1.5, 180]}
MO_init_dicts_list: [{'type': 'MOa' , 'pose': [-1.5, 0, 90]}]